
export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_USERS: "VIEW_USERS",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_REPORTS: "VIEW_REPORTS",
  VIEW_SETTINGS: "VIEW_SETTINGS",
};
